export class ArrayBuilder {
    /**
     * Builds an array of length `length` using the provided resolver function.
     * @param length The length of the array to build.
     * @param resolver A function that takes an index and returns a value for that index.
     * @returns An array of type T with values generated by the resolver function.
     */
    public static build<T>(length: number, resolver: (index: number) => T): T[] {
        return Array.from({ length }, (_, i) => resolver(i));
    }
}
