export type DigitalCrudEndpoint = 'user' | 'page' | 'page/asset';

export type DigitalEndpoint =
    | 'authentication/user/login'
    | 'authentication/user/refresh'
    | 'authentication/user/logout'
    | 'authentication/user/logout-all'
    | 'user'
    | 'user/:id'
    | 'user/:id/avatar'
    | 'user/:id/password'
    | 'user/self'
    | 'user/schema'
    | 'page'
    | 'page/:id'
    | 'page/path/:path'
    | 'page/schema'
    | 'page/asset'
    | 'page/asset/:id'
    | 'page/asset/path/:path'
    | 'page/asset/upload'
    | 'validation/pattern/email'
    | 'validation/pattern/username'
    | 'validation/pattern/password'
    | 'validation/size/avatar';
