export type JsonLdStatus = 'Required' | 'Recommended' | 'Optional' | 'Conditional';

export interface JsonLdPropertySpec {
    property: string;
    valueType: string;
    status: JsonLdStatus;
    description: string;
}

export interface JsonLdTypeSpec {
    feature: string;
    properties: JsonLdPropertySpec[];
}

export const JSONLD_TYPES: Record<string, JsonLdTypeSpec> = {
    Accommodation: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Accommodation' },
            { property: 'occupancy', valueType: 'QuantitativeValue', status: 'Required', description: 'Maximum guest capacity' },
            { property: 'additionalType', valueType: 'Text', status: 'Recommended', description: 'EntirePlace | PrivateRoom | SharedRoom' },
            { property: 'bed', valueType: 'BedDetails', status: 'Recommended', description: 'Bed types and quantities' },
            { property: 'amenityFeature', valueType: 'LocationFeatureSpecification', status: 'Recommended', description: 'Boolean and non-boolean amenities' },
            { property: 'floorSize', valueType: 'QuantitativeValue', status: 'Recommended', description: 'Size in FTK/SQFT or MTK/SQM' },
            { property: 'numberOfBathroomsTotal', valueType: 'Integer', status: 'Recommended', description: 'Total bathrooms count' },
            { property: 'numberOfBedrooms', valueType: 'Integer', status: 'Recommended', description: 'Total bedrooms count' },
            { property: 'numberOfRooms', valueType: 'Integer', status: 'Recommended', description: 'Total rooms count' },
            { property: 'petsAllowed', valueType: 'Boolean', status: 'Optional', description: 'Pet policy' },
            { property: 'smokingAllowed', valueType: 'Boolean', status: 'Optional', description: 'Smoking policy' },
        ],
    },
    AggregateRating: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'AggregateRating' },
            { property: 'ratingValue', valueType: 'Number|Text', status: 'Required', description: 'Average rating across all reviews' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended', description: 'Highest scale value (default 5)' },
            { property: 'ratingCount', valueType: 'Number', status: 'Required', description: 'Total number of ratings' },
            { property: 'reviewCount', valueType: 'Number', status: 'Required', description: 'Number of reviews submitted' },
            { property: 'itemReviewed', valueType: 'Thing', status: 'Required', description: 'Item being rated (omit if nested)' },
            { property: 'itemReviewed.name', valueType: 'Text', status: 'Required', description: 'Name of rated item' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended', description: 'Lowest scale value (default 1)' },
        ],
    },
    Answer: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Answer' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Full answer to the question (may contain HTML)' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Answer author information' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'Profile page link for answer author' },
            { property: 'upvoteCount', valueType: 'Integer', status: 'Recommended', description: 'Total votes for this answer' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Direct link to specific answer' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended', description: 'ISO 8601 answer creation date' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'ISO 8601 edit date' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended', description: 'Distinguishes human from AI content' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended', description: 'Clarifications about the answer' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended', description: 'Number of comments on answer' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Inline images within answer' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Inline videos within answer' },
        ],
    },
    Article: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Article | NewsArticle | BlogPosting' },
            { property: 'headline', valueType: 'Text', status: 'Recommended', description: 'Title of the article' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Representative image URL' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended', description: 'First published date in ISO 8601' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Most recently modified date in ISO 8601' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Author of the article' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended', description: 'Name of the author' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'URL uniquely identifying the author' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional', description: 'Publishing organization' },
        ],
    },
    BedDetails: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'BedDetails' },
            { property: 'numberOfBeds', valueType: 'Integer', status: 'Recommended', description: 'Quantity of beds' },
            { property: 'typeOfBed', valueType: 'Text', status: 'Recommended', description: 'Queen | King | Single | Double | etc.' },
        ],
    },
    BlogPosting: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'BlogPosting' },
            { property: 'headline', valueType: 'Text', status: 'Recommended', description: 'Title of the article' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Representative image URL' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended', description: 'First published date in ISO 8601' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Most recently modified date in ISO 8601' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Author of the article' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended', description: 'Name of the author' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'URL uniquely identifying the author' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional', description: 'Publishing organization' },
        ],
    },
    Book: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', description: 'https://schema.org' },
            { property: '@id', valueType: 'Text', status: 'Required', description: 'Globally unique stable URL identifier' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Book' },
            { property: 'author', valueType: 'Person|Organization', status: 'Required', description: 'Book creator(s)' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Book title' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'Page where book is introduced or described' },
            { property: 'workExample', valueType: 'Book', status: 'Required', description: 'Edition(s) of the work' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended', description: 'Reference page (Wikipedia or Wikidata)' },
            { property: 'bookFormat', valueType: 'Enum', status: 'Required', description: 'Audiobook | EBook | Hardcover | Paperback' },
            { property: 'inLanguage', valueType: 'Text', status: 'Required', description: 'Two-letter ISO 639-1 language code' },
            { property: 'isbn', valueType: 'Text', status: 'Required', description: 'ISBN-13 identifier' },
            { property: 'potentialAction', valueType: 'ReadAction|BorrowAction', status: 'Required', description: 'Purchase or borrowing mechanism' },
            { property: 'bookEdition', valueType: 'Text', status: 'Recommended', description: 'Edition information (e.g. 2nd Edition)' },
            { property: 'datePublished', valueType: 'Date', status: 'Recommended', description: 'Publication date YYYY-MM-DD or YYYY' },
            { property: 'identifier', valueType: 'PropertyValue', status: 'Recommended', description: 'OCLC / LCCN / JP e-code' },
        ],
    },
    BorrowAction: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'BorrowAction' },
            { property: 'lender', valueType: 'LibrarySystem', status: 'Required', description: 'Library providing access' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required', description: 'Deep link specifications' },
            { property: 'target.@type', valueType: 'Text', status: 'Required', description: 'EntryPoint' },
            { property: 'target.actionPlatform', valueType: 'Text', status: 'Required', description: 'DesktopWeb | Android | iOS' },
            { property: 'target.urlTemplate', valueType: 'URL', status: 'Required', description: 'Direct link to borrowing page' },
        ],
    },
    Brand: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Brand' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Brand ID name' },
        ],
    },
    BreadcrumbList: {
        feature: 'Breadcrumb',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'BreadcrumbList' },
            { property: 'itemListElement', valueType: 'ListItem[]', status: 'Required', description: 'Array of breadcrumbs in specific order' },
        ],
    },
    BroadcastEvent: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'BroadcastEvent' },
            { property: 'isLiveBroadcast', valueType: 'Boolean', status: 'Required', description: 'Set to true for livestreams' },
            { property: 'startDate', valueType: 'DateTime', status: 'Required', description: 'Livestream start time in ISO 8601' },
            { property: 'endDate', valueType: 'DateTime', status: 'Required', description: 'Livestream end time in ISO 8601' },
        ],
    },
    Certification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Certification' },
            { property: 'issuedBy', valueType: 'Organization', status: 'Required', description: 'Certifying authority' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Certification name' },
            { property: 'certificationIdentification', valueType: 'Text', status: 'Recommended', description: 'Certification code or identifier' },
            { property: 'certificationRating', valueType: 'Rating', status: 'Recommended', description: 'Certification value or rating' },
        ],
    },
    Claim: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Claim' },
            { property: 'appearance', valueType: 'URL|CreativeWork', status: 'Recommended', description: 'Reference to work where claim appears' },
            { property: 'author', valueType: 'Organization|Person', status: 'Recommended', description: 'Originator of the claim being fact-checked' },
            { property: 'datePublished', valueType: 'DateTime|Date', status: 'Recommended', description: 'When the claim entered public discourse' },
            { property: 'firstAppearance', valueType: 'URL|CreativeWork', status: 'Recommended', description: 'Reference to where claim first appeared' },
        ],
    },
    ClaimReview: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ClaimReview' },
            { property: 'claimReviewed', valueType: 'Text', status: 'Required', description: 'Short summary of claim being evaluated (max 75 chars)' },
            { property: 'reviewRating', valueType: 'Rating', status: 'Required', description: 'Assessment outcome of the claim' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'Link to page hosting complete fact check' },
            { property: 'author', valueType: 'Organization|Person', status: 'Recommended', description: 'Publisher creating the fact check' },
            { property: 'itemReviewed', valueType: 'Claim|CreativeWork', status: 'Recommended', description: 'Object describing the claim being evaluated' },
        ],
    },
    Clip: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Clip' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Descriptive title for clip segment' },
            { property: 'startOffset', valueType: 'Number', status: 'Required', description: 'Clip start time in seconds from beginning' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'Points to clip start time with query parameters' },
            { property: 'endOffset', valueType: 'Number', status: 'Recommended', description: 'Clip end time in seconds from beginning' },
        ],
    },
    Comment: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Comment' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Comment author information' },
            { property: 'author.name', valueType: 'Text', status: 'Required', description: 'Commenter name' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'Profile page for comment author' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required', description: 'ISO 8601 comment timestamp' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Comment content (required if no image/video)' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Inline images within comment' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Inline videos within comment' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Specific comment URL' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended', description: 'Nested threaded replies' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended', description: 'Number of nested comments' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'Engagement metrics' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Last edit timestamp' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended', description: 'Status (e.g. Deleted)' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended', description: 'Human vs machine-generated indicator' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended', description: 'Referenced content' },
        ],
    },
    Course: {
        feature: 'CourseList',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Title of the course' },
            { property: 'description', valueType: 'Text', status: 'Required', description: 'Description of the course (max 60 chars display)' },
            { property: 'provider', valueType: 'Organization', status: 'Recommended', description: 'Organization that publishes the course content' },
            { property: 'url', valueType: 'URL', status: 'Optional', description: 'URL for the course' },
        ],
    },
    CreativeWork: {
        feature: 'PaywalledContent',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Article | NewsArticle | Blog | Comment | Course | HowTo | Message | Review | WebPage' },
            { property: 'isAccessibleForFree', valueType: 'Boolean', status: 'Required', description: 'Set to false for paywalled sections' },
            { property: 'hasPart', valueType: 'WebPageElement', status: 'Recommended', description: 'Object identifying paywalled sections' },
            { property: 'hasPart.@type', valueType: 'Text', status: 'Recommended', description: 'WebPageElement' },
            { property: 'hasPart.isAccessibleForFree', valueType: 'Boolean', status: 'Recommended', description: 'Set to false for paywalled sections' },
            { property: 'hasPart.cssSelector', valueType: 'CssSelectorType', status: 'Recommended', description: 'CSS class selector referencing HTML paywall element' },
            { property: 'headline', valueType: 'Text', status: 'Optional', description: 'Article title' },
            { property: 'image', valueType: 'URL', status: 'Optional', description: 'Thumbnail image URL' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Optional', description: 'Publication timestamp' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Optional', description: 'Last modification timestamp' },
            { property: 'author', valueType: 'Person', status: 'Optional', description: 'Content creator information' },
            { property: 'description', valueType: 'Text', status: 'Optional', description: 'Brief content summary' },
            { property: 'mainEntityOfPage', valueType: 'WebPage', status: 'Optional', description: 'Reference to main page entity' },
        ],
    },
    DataCatalog: {
        feature: 'Dataset',
        properties: [
            { property: 'includedInDataCatalog', valueType: 'DataCatalog', status: 'Recommended', description: 'Catalog to which dataset belongs' },
        ],
    },
    DataDownload: {
        feature: 'Dataset',
        properties: [
            { property: 'distribution', valueType: 'DataDownload', status: 'Recommended', description: 'Download location and format details' },
            { property: 'distribution.contentUrl', valueType: 'URL', status: 'Required', description: 'Download link' },
            { property: 'distribution.encodingFormat', valueType: 'Text|URL', status: 'Recommended', description: 'File format specification' },
        ],
    },
    DataFeed: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'DataFeed' },
            { property: 'dataFeedElement', valueType: 'Book|LibrarySystem', status: 'Required', description: 'Contains book or library entities' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Required', description: 'Last feed update in ISO 8601 format' },
        ],
    },
    Dataset: {
        feature: 'Dataset',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Descriptive dataset identifier' },
            { property: 'description', valueType: 'Text', status: 'Required', description: 'Summary of 50-5000 characters' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended', description: 'Alternative names or aliases' },
            { property: 'creator', valueType: 'Person|Organization', status: 'Recommended', description: 'Author with ORCID or ROR ID' },
            { property: 'citation', valueType: 'Text|CreativeWork', status: 'Recommended', description: 'Related academic articles' },
            { property: 'funder', valueType: 'Person|Organization', status: 'Recommended', description: 'Financial supporters' },
            { property: 'hasPart', valueType: 'URL|Dataset', status: 'Recommended', description: 'Subset relationship' },
            { property: 'isPartOf', valueType: 'URL|Dataset', status: 'Recommended', description: 'Parent relationship' },
            { property: 'identifier', valueType: 'URL|Text|PropertyValue', status: 'Recommended', description: 'DOI or Compact Identifier' },
            { property: 'isAccessibleForFree', valueType: 'Boolean', status: 'Recommended', description: 'Free access status' },
            { property: 'keywords', valueType: 'Text', status: 'Recommended', description: 'Topic summaries' },
            { property: 'license', valueType: 'URL|CreativeWork', status: 'Recommended', description: 'Distribution license' },
            { property: 'measurementTechnique', valueType: 'Text|URL', status: 'Recommended', description: 'Methodology employed' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended', description: 'Canonical dataset reference' },
            { property: 'spatialCoverage', valueType: 'Text|Place', status: 'Recommended', description: 'Geographic scope' },
            { property: 'temporalCoverage', valueType: 'Text', status: 'Recommended', description: 'Time period in ISO 8601 format' },
            { property: 'variableMeasured', valueType: 'Text|PropertyValue', status: 'Recommended', description: 'Measured variables' },
            { property: 'version', valueType: 'Text|Number', status: 'Recommended', description: 'Release number' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Dataset description page' },
        ],
    },
    DiscussionForumPosting: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'DiscussionForumPosting | SocialMediaPosting' },
            { property: 'author', valueType: 'Person|Organization', status: 'Required', description: 'Post creator information' },
            { property: 'author.name', valueType: 'Text', status: 'Required', description: 'Creator name' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'Link to creator profile' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required', description: 'ISO 8601 publication timestamp' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Post content (required if no image/video)' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Inline post images' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Inline post videos' },
            { property: 'headline', valueType: 'Text', status: 'Recommended', description: 'Post title' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Canonical post URL' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended', description: 'Nested responses' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended', description: 'Total response count' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'Engagement metrics' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Last edit timestamp' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended', description: 'Status (e.g. Deleted)' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended', description: 'Content origin type' },
            { property: 'isPartOf', valueType: 'CreativeWork|URL', status: 'Recommended', description: 'Parent forum/subforum' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended', description: 'Referenced content' },
        ],
    },
    EmployerAggregateRating: {
        feature: 'EmployerRating',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'EmployerAggregateRating' },
            { property: 'itemReviewed', valueType: 'Organization', status: 'Required', description: 'Organization being rated' },
            { property: 'ratingCount', valueType: 'Number', status: 'Required', description: 'Total count of ratings' },
            { property: 'ratingValue', valueType: 'Number|Text', status: 'Required', description: 'Numerical quality assessment' },
            { property: 'reviewCount', valueType: 'Number', status: 'Required', description: 'Count of individuals who submitted reviews' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended', description: 'Highest permissible rating value (default 5)' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended', description: 'Lowest permissible rating value (default 1)' },
        ],
    },
    Event: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Event' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Full title of the event' },
            { property: 'startDate', valueType: 'DateTime', status: 'Required', description: 'Event start in ISO-8601 format with timezone' },
            { property: 'location', valueType: 'Place', status: 'Required', description: 'Physical venue details' },
            { property: 'location.address', valueType: 'PostalAddress', status: 'Required', description: 'Venue detailed street address' },
            { property: 'location.name', valueType: 'Text', status: 'Recommended', description: 'Name of venue or location' },
            { property: 'endDate', valueType: 'DateTime', status: 'Recommended', description: 'End date and end time of the event' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Event details and context' },
            { property: 'eventStatus', valueType: 'EventStatusType', status: 'Recommended', description: 'EventScheduled | EventCancelled | EventMovedOnline | EventPostponed | EventRescheduled' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Event logo or promotional imagery' },
            { property: 'offers', valueType: 'Offer', status: 'Recommended', description: 'Ticketing information' },
            { property: 'organizer', valueType: 'Organization|Person', status: 'Recommended', description: 'Host details' },
            { property: 'performer', valueType: 'Person|PerformingGroup', status: 'Recommended', description: 'Participating artists or performers' },
            { property: 'previousStartDate', valueType: 'DateTime', status: 'Optional', description: 'Previously scheduled start date if rescheduled' },
        ],
    },
    FAQPage: {
        feature: 'FAQ',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'FAQPage' },
            { property: 'mainEntity', valueType: 'Question[]', status: 'Required', description: 'Array of Question elements with answered questions' },
        ],
    },
    HowToDirection: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'HowToDirection' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Text of the direction' },
        ],
    },
    HowToSection: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'HowToSection' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Name of the section' },
            { property: 'itemListElement', valueType: 'HowToStep[]', status: 'Required', description: 'List of detailed steps for the section' },
        ],
    },
    HowToStep: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'HowToStep' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Full instruction text of this step' },
            { property: 'itemListElement', valueType: 'HowToDirection[]|HowToTip[]', status: 'Optional', description: 'List of detailed substeps' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Image for the step' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Word or short phrase summarizing the step' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'URL linking directly to the step' },
            { property: 'video', valueType: 'VideoObject|Clip', status: 'Recommended', description: 'Video for this step or clip of video' },
        ],
    },
    HowToTip: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'HowToTip' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Text of the tip' },
        ],
    },
    ImageObject: {
        feature: 'ImageMetadata',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ImageObject' },
            { property: 'contentUrl', valueType: 'URL', status: 'Required', description: 'URL to the actual image content' },
            { property: 'creator', valueType: 'Organization|Person', status: 'Required', description: 'Individual or entity that produced the photograph' },
            { property: 'creator.name', valueType: 'Text', status: 'Required', description: 'Name identifier for the photographer' },
            { property: 'creditText', valueType: 'Text', status: 'Required', description: 'Name of person or organization credited for image' },
            { property: 'copyrightNotice', valueType: 'Text', status: 'Required', description: 'Copyright notice for the photograph' },
            { property: 'license', valueType: 'URL', status: 'Required', description: 'URL to page describing the license governing image use' },
            { property: 'acquireLicensePage', valueType: 'URL', status: 'Recommended', description: 'URL to page for licensing the image' },
            { property: 'url', valueType: 'URL', status: 'Optional', description: 'Alternative to contentUrl for image location' },
        ],
    },
    InteractionCounter: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'InteractionCounter' },
            { property: 'userInteractionCount', valueType: 'Number', status: 'Required', description: 'Numeric count of interactions' },
            { property: 'interactionType', valueType: 'Action', status: 'Required', description: 'LikeAction | DislikeAction | ViewAction | CommentAction | ReplyAction | ShareAction' },
        ],
    },
    ItemList: {
        feature: 'Carousel',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ItemList' },
            { property: 'itemListElement', valueType: 'ListItem[]', status: 'Required', description: 'List of at least two ListItem elements' },
        ],
    },
    JobPosting: {
        feature: 'JobPosting',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'JobPosting' },
            { property: 'datePosted', valueType: 'Date', status: 'Required', description: 'Original date employer posted the job in ISO 8601' },
            { property: 'description', valueType: 'Text', status: 'Required', description: 'Full description of the job in HTML format' },
            { property: 'hiringOrganization', valueType: 'Organization', status: 'Required', description: 'Company offering the position' },
            { property: 'jobLocation', valueType: 'Place', status: 'Required', description: 'Physical work location with PostalAddress' },
            { property: 'title', valueType: 'Text', status: 'Required', description: 'Job title only' },
            { property: 'applicantLocationRequirements', valueType: 'AdministrativeArea', status: 'Recommended', description: 'Geographic location(s) for remote employees' },
            { property: 'baseSalary', valueType: 'MonetaryAmount', status: 'Recommended', description: 'Actual base salary with currency and QuantitativeValue' },
            { property: 'directApply', valueType: 'Boolean', status: 'Recommended', description: 'Whether URL enables direct job application' },
            { property: 'employmentType', valueType: 'Text', status: 'Recommended', description: 'FULL_TIME | PART_TIME | CONTRACTOR | TEMPORARY | INTERN | VOLUNTEER | PER_DIEM | OTHER' },
            { property: 'identifier', valueType: 'PropertyValue', status: 'Recommended', description: 'Hiring organization unique job identifier' },
            { property: 'jobLocationType', valueType: 'Text', status: 'Recommended', description: 'TELECOMMUTE for 100% remote positions' },
            { property: 'validThrough', valueType: 'DateTime', status: 'Recommended', description: 'Expiration date in ISO 8601 format' },
            { property: 'educationRequirements', valueType: 'EducationalOccupationalCredential', status: 'Optional', description: 'Required education level' },
            { property: 'experienceRequirements', valueType: 'OccupationalExperienceRequirements', status: 'Optional', description: 'Minimum experience needed' },
            { property: 'experienceInPlaceOfEducation', valueType: 'Boolean', status: 'Optional', description: 'Whether experience can substitute education' },
        ],
    },
    Library: {
        feature: 'Book',
        properties: [
            { property: '@id', valueType: 'URL', status: 'Required', description: 'Unique branch identifier' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Library' },
            { property: 'location', valueType: 'PostalAddress', status: 'Required', description: 'Branch physical address' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Branch name' },
            { property: 'location.@type', valueType: 'Text', status: 'Required', description: 'PostalAddress' },
            { property: 'location.addressCountry', valueType: 'Text', status: 'Required', description: 'ISO 3166-1 country code' },
            { property: 'location.addressLocality', valueType: 'Text', status: 'Required', description: 'City or locality' },
            { property: 'location.addressRegion', valueType: 'Text', status: 'Required', description: 'State or region' },
            { property: 'location.postalCode', valueType: 'Text', status: 'Required', description: 'ZIP or postal code' },
            { property: 'location.streetAddress', valueType: 'Text', status: 'Required', description: 'Street address line' },
        ],
    },
    LibrarySystem: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', description: 'https://schema.org' },
            { property: '@id', valueType: 'URL', status: 'Required', description: 'Stable unique system identifier' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'LibrarySystem' },
            { property: 'additionalProperty', valueType: 'PropertyValue', status: 'Required', description: 'Library type indicator' },
            { property: 'member', valueType: 'Library', status: 'Required', description: 'Member library branches' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'System name' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'System introduction/description page' },
            { property: 'additionalProperty.@type', valueType: 'Text', status: 'Required', description: 'PropertyValue' },
            { property: 'additionalProperty.name', valueType: 'Text', status: 'Required', description: 'librarytype' },
            { property: 'additionalProperty.value', valueType: 'Text', status: 'Required', description: 'public | academic | corporate | government | school | special' },
        ],
    },
    ListItem: {
        feature: 'Breadcrumb',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ListItem' },
            { property: 'position', valueType: 'Integer', status: 'Required', description: 'Ordinal position of the item page in the list' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'User-displayed breadcrumb title' },
            { property: 'item', valueType: 'URL|Thing', status: 'Required', description: 'URL to the webpage that represents the breadcrumb (optional for last item)' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'Canonical URL of the item detail page' },
            { property: 'item.name', valueType: 'Text', status: 'Required', description: 'String name of the item displayed as carousel title' },
            { property: 'item.url', valueType: 'URL', status: 'Required', description: 'Fully-qualified URL and page anchor to this item' },
        ],
    },
    LocalBusiness: {
        feature: 'LocalBusiness',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'LocalBusiness (or subtype: Restaurant / Store / etc.)' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Business name' },
            { property: 'address', valueType: 'PostalAddress', status: 'Required', description: 'Physical location' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Average rating from multiple reviews' },
            { property: 'department', valueType: 'LocalBusiness', status: 'Recommended', description: 'Nested departments with distinct properties' },
            { property: 'geo', valueType: 'GeoCoordinates', status: 'Recommended', description: 'Geographic coordinates (min 5 decimal places)' },
            { property: 'menu', valueType: 'URL', status: 'Recommended', description: 'Fully-qualified menu URL (food establishments)' },
            { property: 'openingHoursSpecification', valueType: 'OpeningHoursSpecification', status: 'Recommended', description: 'Business hours' },
            { property: 'priceRange', valueType: 'Text', status: 'Recommended', description: 'Relative pricing (max 100 characters)' },
            { property: 'review', valueType: 'Review', status: 'Recommended', description: 'Customer review' },
            { property: 'servesCuisine', valueType: 'Text', status: 'Recommended', description: 'Restaurant cuisine type' },
            { property: 'telephone', valueType: 'Text', status: 'Recommended', description: 'Primary contact number with country and area codes' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Fully-qualified business location URL' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Optional', description: 'Multiple images (16x9 / 4x3 / 1x1 ratios)' },
        ],
    },
    LocationFeatureSpecification: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'LocationFeatureSpecification' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Feature name (ac / wifi / pool / etc.)' },
            { property: 'value', valueType: 'Boolean|Text', status: 'Required', description: 'True/false or descriptive value' },
        ],
    },
    MathSolver: {
        feature: 'MathSolver',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'MathSolver and LearningResource' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Title of the math solver tool' },
            { property: 'url', valueType: 'URL', status: 'Required', description: 'Homepage URL of the solver' },
            { property: 'usageInfo', valueType: 'URL', status: 'Required', description: 'Privacy policy for the math solving site' },
            { property: 'inLanguage', valueType: 'Text', status: 'Recommended', description: 'Supported language codes' },
            { property: 'potentialAction', valueType: 'SolveMathAction', status: 'Required', description: 'Action leading to mathematical explanations' },
            { property: 'assesses', valueType: 'Text', status: 'Recommended', description: 'Problem types solved' },
            { property: 'learningResourceType', valueType: 'Text', status: 'Required', description: 'Math Solver' },
        ],
    },
    MonetaryAmount: {
        feature: 'JobPosting',
        properties: [
            { property: 'currency', valueType: 'Text', status: 'Required', description: 'Currency code' },
            { property: 'value', valueType: 'QuantitativeValue', status: 'Required', description: 'Salary value or range with unitText' },
        ],
    },
    Movie: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Movie' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Movie title' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required', description: '6:9 aspect ratio poster' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Movie page URL' },
            { property: 'dateCreated', valueType: 'Date|DateTime', status: 'Recommended', description: 'Movie release date' },
            { property: 'director', valueType: 'Person', status: 'Recommended', description: 'Film director information' },
            { property: 'review', valueType: 'Review', status: 'Recommended', description: 'Individual review' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Average rating data' },
        ],
    },
    NewsArticle: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'NewsArticle' },
            { property: 'headline', valueType: 'Text', status: 'Recommended', description: 'Title of the article' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Representative image URL' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended', description: 'First published date in ISO 8601' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Most recently modified date in ISO 8601' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Author of the article' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended', description: 'Name of the author' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'URL uniquely identifying the author' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional', description: 'Publishing organization' },
        ],
    },
    Offer: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Offer' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Direct link to buy tickets' },
            { property: 'price', valueType: 'Number', status: 'Recommended', description: 'Lowest available ticket price' },
            { property: 'priceCurrency', valueType: 'Text', status: 'Required', description: 'ISO 4217 three-letter currency code' },
            { property: 'availability', valueType: 'ItemAvailability', status: 'Recommended', description: 'InStock | OutOfStock | PreOrder | Discontinued' },
            { property: 'validFrom', valueType: 'DateTime', status: 'Recommended', description: 'When tickets go on sale' },
            { property: 'priceSpecification', valueType: 'UnitPriceSpecification', status: 'Optional', description: 'Complex pricing via specifications' },
            { property: 'hasMerchantReturnPolicy', valueType: 'MerchantReturnPolicy', status: 'Recommended', description: 'Return policy details for offer' },
            { property: 'itemCondition', valueType: 'OfferItemCondition', status: 'Recommended', description: 'NewCondition | UsedCondition | RefurbishedCondition' },
            { property: 'priceValidUntil', valueType: 'Date', status: 'Recommended', description: 'Date after which price is no longer available' },
            { property: 'shippingDetails', valueType: 'OfferShippingDetails', status: 'Recommended', description: 'Shipping policy information' },
        ],
    },
    OfferShippingDetails: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'OfferShippingDetails' },
            { property: 'shippingRate', valueType: 'MonetaryAmount', status: 'Recommended', description: 'Shipping cost amount and currency' },
            { property: 'shippingDestination', valueType: 'DefinedRegion', status: 'Recommended', description: 'Geographic shipping region' },
            { property: 'deliveryTime', valueType: 'ShippingDeliveryTime', status: 'Recommended', description: 'Processing and transit timeframes' },
        ],
    },
    OpeningHoursSpecification: {
        feature: 'LocalBusiness',
        properties: [
            { property: 'closes', valueType: 'Time', status: 'Recommended', description: 'Closing time in hh:mm:ss' },
            { property: 'dayOfWeek', valueType: 'DayOfWeek', status: 'Recommended', description: 'Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday' },
            { property: 'opens', valueType: 'Time', status: 'Recommended', description: 'Opening time in hh:mm:ss' },
            { property: 'validFrom', valueType: 'Date', status: 'Recommended', description: 'Seasonal closure start (YYYY-MM-DD)' },
            { property: 'validThrough', valueType: 'Date', status: 'Recommended', description: 'Seasonal closure end (YYYY-MM-DD)' },
        ],
    },
    Organization: {
        feature: 'CourseList',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Organization name offering the course' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended', description: 'Links to social or review profiles' },
            { property: 'logo', valueType: 'URL|ImageObject', status: 'Recommended', description: 'Representative organizational logo' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Organization' },
            { property: 'address', valueType: 'PostalAddress', status: 'Recommended', description: 'Physical or mailing address' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended', description: 'Common alternate business names' },
            { property: 'contactPoint', valueType: 'ContactPoint', status: 'Recommended', description: 'Primary customer contact method' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Detailed organizational overview' },
            { property: 'email', valueType: 'Text', status: 'Recommended', description: 'Business email address' },
            { property: 'foundingDate', valueType: 'Date', status: 'Recommended', description: 'Establishment date in ISO 8601' },
            { property: 'globalLocationNumber', valueType: 'Text', status: 'Recommended', description: 'GS1 Global Location Number' },
            { property: 'hasMerchantReturnPolicy', valueType: 'MerchantReturnPolicy', status: 'Recommended', description: 'Return policies' },
            { property: 'hasMemberProgram', valueType: 'MemberProgram', status: 'Recommended', description: 'Loyalty or membership programs' },
            { property: 'hasShippingService', valueType: 'ShippingService', status: 'Recommended', description: 'Shipping policies' },
            { property: 'iso6523Code', valueType: 'Text', status: 'Recommended', description: 'ISO 6523 identifier with ICD prefix' },
            { property: 'legalName', valueType: 'Text', status: 'Recommended', description: 'Registered legal name' },
            { property: 'leiCode', valueType: 'Text', status: 'Recommended', description: 'ISO 17442 legal entity identifier' },
            { property: 'numberOfEmployees', valueType: 'QuantitativeValue', status: 'Recommended', description: 'Employee count or range' },
            { property: 'telephone', valueType: 'Text', status: 'Recommended', description: 'Primary business phone number' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Organization website' },
            { property: 'vatID', valueType: 'Text', status: 'Recommended', description: 'VAT tax code' },
            { property: 'duns', valueType: 'Text', status: 'Optional', description: 'Dun and Bradstreet DUNS number' },
            { property: 'naics', valueType: 'Text', status: 'Optional', description: 'North American Industry Classification System code' },
            { property: 'taxID', valueType: 'Text', status: 'Optional', description: 'Tax identification associated with organization' },
        ],
    },
    PeopleAudience: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'PeopleAudience' },
            { property: 'suggestedGender', valueType: 'Text|GenderType', status: 'Recommended', description: 'Male | Female | Unisex' },
            { property: 'suggestedMinAge', valueType: 'Number', status: 'Recommended', description: 'Minimum age in years' },
            { property: 'suggestedMaxAge', valueType: 'Number', status: 'Recommended', description: 'Maximum age in years' },
        ],
    },
    Person: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Person' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Primary identifier (real name or social handle)' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended', description: 'Alternate public identifier' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'User byline or applicable credential' },
            { property: 'identifier', valueType: 'Text', status: 'Recommended', description: 'Unique site-specific identifier' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Recommended', description: 'Profile image (min 50K pixels)' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended', description: 'Links to external profiles or home pages' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'Platform-specific engagement metrics' },
            { property: 'agentInteractionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'Entity own activity stats' },
        ],
    },
    Place: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Place' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Venue name' },
            { property: 'address', valueType: 'PostalAddress', status: 'Required', description: 'Complete address details' },
        ],
    },
    PostalAddress: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'PostalAddress' },
            { property: 'streetAddress', valueType: 'Text', status: 'Recommended', description: 'Full street address including unit number' },
            { property: 'addressLocality', valueType: 'Text', status: 'Recommended', description: 'City or locality' },
            { property: 'addressRegion', valueType: 'Text', status: 'Recommended', description: 'State region or province' },
            { property: 'postalCode', valueType: 'Text', status: 'Recommended', description: 'ZIP or postal code' },
            { property: 'addressCountry', valueType: 'Text', status: 'Recommended', description: 'Two-letter ISO 3166-1 alpha-2 country code' },
        ],
    },
    Product: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Product' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Name of the product' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required', description: 'Product photos (min 50K pixels - 16x9/4x3/1x1)' },
            { property: 'offers', valueType: 'Offer', status: 'Required', description: 'Nested offer to sell the product' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Combined ratings from multiple reviews' },
            { property: 'audience', valueType: 'PeopleAudience', status: 'Recommended', description: 'Suggested audience info' },
            { property: 'brand', valueType: 'Brand', status: 'Recommended', description: 'Producer or manufacturer entity' },
            { property: 'color', valueType: 'Text', status: 'Recommended', description: 'Color or color combination' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Product description' },
            { property: 'gtin', valueType: 'Text', status: 'Recommended', description: 'Global Trade Item Number' },
            { property: 'gtin8', valueType: 'Text', status: 'Recommended', description: '8-digit GTIN' },
            { property: 'gtin12', valueType: 'Text', status: 'Recommended', description: '12-digit GTIN (UPC)' },
            { property: 'gtin13', valueType: 'Text', status: 'Recommended', description: '13-digit GTIN (EAN)' },
            { property: 'gtin14', valueType: 'Text', status: 'Recommended', description: '14-digit GTIN' },
            { property: 'hasCertification', valueType: 'Certification', status: 'Recommended', description: 'Energy efficiency or product certifications' },
            { property: 'inProductGroupWithID', valueType: 'Text', status: 'Recommended', description: 'Product group identifier for variants' },
            { property: 'isVariantOf', valueType: 'ProductGroup', status: 'Recommended', description: 'Product group for variants' },
            { property: 'material', valueType: 'Text', status: 'Recommended', description: 'Material composition' },
            { property: 'mpn', valueType: 'Text', status: 'Recommended', description: 'Manufacturer part number' },
            { property: 'pattern', valueType: 'Text', status: 'Recommended', description: 'Pattern details (polka dots / striped / etc.)' },
            { property: 'review', valueType: 'Review', status: 'Recommended', description: 'Individual product review' },
            { property: 'size', valueType: 'Text|SizeSpecification', status: 'Recommended', description: 'Product size designation' },
            { property: 'sku', valueType: 'Text', status: 'Recommended', description: 'Merchant-specific product identifier' },
            { property: 'subjectOf', valueType: '3DModel', status: 'Recommended', description: 'Link to glTF-format 3D model' },
        ],
    },
    ProfilePage: {
        feature: 'ProfilePage',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ProfilePage' },
            { property: 'mainEntity', valueType: 'Person|Organization', status: 'Required', description: 'Person or organization this profile page is about' },
            { property: 'dateCreated', valueType: 'DateTime', status: 'Recommended', description: 'Profile creation date in ISO 8601' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Last modification date in ISO 8601' },
            { property: 'hasPart', valueType: 'Article', status: 'Optional', description: 'Recent activity or content by the creator' },
        ],
    },
    PropertyValue: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'PropertyValue' },
            { property: 'propertyID', valueType: 'Text', status: 'Required', description: 'ID type: OCLC_NUMBER | LCCN | JP_E-CODE' },
            { property: 'value', valueType: 'Text', status: 'Required', description: 'Numeric identifier without prefixes' },
        ],
    },
    QAPage: {
        feature: 'QAPage',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'QAPage' },
            { property: 'mainEntity', valueType: 'Question', status: 'Required', description: 'The Question for this page' },
        ],
    },
    Question: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Question' },
            { property: 'acceptedAnswer', valueType: 'Answer', status: 'Conditional', description: 'Top answer accepted by asker or moderator' },
            { property: 'eduQuestionType', valueType: 'Text', status: 'Required', description: 'Flashcard' },
            { property: 'text', valueType: 'Text', status: 'Recommended', description: 'Full text of the long form of the question' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Full text of the short form of the question' },
            { property: 'answerCount', valueType: 'Integer', status: 'Required', description: 'Total number of answers' },
            { property: 'suggestedAnswer', valueType: 'Answer', status: 'Conditional', description: 'Possible answer not marked as accepted' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Question author information' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'Profile page link for author' },
            { property: 'upvoteCount', valueType: 'Integer', status: 'Recommended', description: 'Total votes received by question' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended', description: 'Clarifications about the question' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended', description: 'Number of comments on question' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended', description: 'ISO 8601 format posting date' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'ISO 8601 format edit date' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended', description: 'Indicates human vs AI-generated content' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Inline images within question' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Inline videos within question' },
        ],
    },
    Quiz: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Quiz' },
            { property: 'hasPart', valueType: 'Question', status: 'Required', description: 'Nested flashcard question for the quiz' },
            { property: 'about', valueType: 'Thing', status: 'Recommended', description: 'Underlying concept behind the quiz' },
            { property: 'about.name', valueType: 'Text', status: 'Recommended', description: 'Name of the concept' },
            { property: 'educationalAlignment', valueType: 'AlignmentObject', status: 'Recommended', description: 'Alignment to educational framework' },
            { property: 'educationalAlignment.alignmentType', valueType: 'Text', status: 'Recommended', description: 'educationalSubject | educationalLevel' },
            { property: 'educationalAlignment.targetName', valueType: 'Text', status: 'Recommended', description: 'Name of node in educational framework' },
        ],
    },
    Rating: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Rating' },
            { property: 'alternateName', valueType: 'Text', status: 'Required', description: 'Human-readable rating label (e.g. True)' },
            { property: 'ratingValue', valueType: 'Number', status: 'Recommended', description: 'Numeric rating within worst-to-best scale' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended', description: 'Highest possible value in the rating scale' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended', description: 'Lowest possible value (minimum 1)' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Alternative to alternateName for rating label' },
        ],
    },
    ReadAction: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'ReadAction' },
            { property: 'expectsAcceptanceOf', valueType: 'Offer', status: 'Required', description: 'User access requirements' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required', description: 'Deep link specifications with platform info' },
            { property: 'expectsAcceptanceOf.@type', valueType: 'Text', status: 'Required', description: 'Offer' },
            { property: 'expectsAcceptanceOf.category', valueType: 'Text', status: 'Required', description: 'nologinrequired | free | subscription | purchase | rental' },
            { property: 'expectsAcceptanceOf.eligibleRegion', valueType: 'Country', status: 'Required', description: 'Geographic availability' },
            { property: 'expectsAcceptanceOf.availabilityEnds', valueType: 'DateTime', status: 'Recommended', description: 'When availability window closes' },
            { property: 'expectsAcceptanceOf.availabilityStarts', valueType: 'DateTime', status: 'Recommended', description: 'When availability window opens' },
            { property: 'expectsAcceptanceOf.price', valueType: 'Number', status: 'Recommended', description: 'Purchase price' },
            { property: 'expectsAcceptanceOf.priceCurrency', valueType: 'Text', status: 'Recommended', description: 'Three-letter ISO 4217 currency code' },
            { property: 'target.@type', valueType: 'Text', status: 'Required', description: 'EntryPoint' },
            { property: 'target.actionPlatform', valueType: 'Text', status: 'Required', description: 'DesktopWeb | Android | iOS' },
            { property: 'target.urlTemplate', valueType: 'URL', status: 'Required', description: 'Direct link to purchase page' },
        ],
    },
    Recipe: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Recipe' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required', description: 'Image of the completed dish' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Name of the dish' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Review score annotation' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended', description: 'Name of person or organization that wrote the recipe' },
            { property: 'cookTime', valueType: 'Duration', status: 'Recommended', description: 'Time to cook the dish in ISO 8601 duration format' },
            { property: 'datePublished', valueType: 'Date', status: 'Recommended', description: 'Date the recipe was published in ISO 8601' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Short summary describing the dish' },
            { property: 'keywords', valueType: 'Text', status: 'Recommended', description: 'Other terms for recipe such as season or holiday' },
            { property: 'nutrition.calories', valueType: 'Energy', status: 'Recommended', description: 'Number of calories per serving' },
            { property: 'prepTime', valueType: 'Duration', status: 'Recommended', description: 'Length of time to prepare ingredients in ISO 8601' },
            { property: 'recipeCategory', valueType: 'Text', status: 'Recommended', description: 'Type of meal or course (dinner / dessert / etc.)' },
            { property: 'recipeCuisine', valueType: 'Text', status: 'Recommended', description: 'Region associated with the recipe' },
            { property: 'recipeIngredient', valueType: 'Text', status: 'Recommended', description: 'An ingredient used in the recipe' },
            { property: 'recipeInstructions', valueType: 'HowToStep|HowToSection|Text', status: 'Recommended', description: 'Steps to make the dish' },
            { property: 'recipeYield', valueType: 'Text|Integer', status: 'Recommended', description: 'Quantity produced by the recipe' },
            { property: 'totalTime', valueType: 'Duration', status: 'Recommended', description: 'Total time to prepare and cook in ISO 8601' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Video depicting steps to make the dish' },
        ],
    },
    Review: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'Review' },
            { property: 'reviewRating', valueType: 'Rating', status: 'Required', description: 'Numerical score given by reviewer' },
            { property: 'author', valueType: 'Person|Organization', status: 'Required', description: 'Author of the review (must be valid name)' },
            { property: 'positiveNotes', valueType: 'ItemList', status: 'Optional', description: 'Pros highlighted in editorial reviews' },
            { property: 'negativeNotes', valueType: 'ItemList', status: 'Optional', description: 'Cons highlighted in editorial reviews' },
            { property: 'itemReviewed', valueType: 'Thing', status: 'Required', description: 'Item being reviewed (omit if nested)' },
            { property: 'itemReviewed.name', valueType: 'Text', status: 'Required', description: 'Name of reviewed item' },
            { property: 'reviewRating.ratingValue', valueType: 'Number|Text', status: 'Required', description: 'Numerical quality rating' },
            { property: 'datePublished', valueType: 'Date', status: 'Required', description: 'Required field for vacation rentals' },
            { property: 'reviewRating.bestRating', valueType: 'Number', status: 'Recommended', description: 'Highest allowed value (default 5)' },
            { property: 'reviewRating.worstRating', valueType: 'Number', status: 'Recommended', description: 'Lowest allowed value (default 1)' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional', description: 'Publishing organization' },
            { property: 'contentReferenceTime', valueType: 'DateTime', status: 'Required', description: 'Required for France-located properties' },
        ],
    },
    SeekToAction: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SeekToAction' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required', description: 'URL with {seek_to_second_number} placeholder' },
            { property: 'startOffset-input', valueType: 'Text', status: 'Required', description: 'required name=seek_to_second_number' },
        ],
    },
    SizeSpecification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SizeSpecification' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Human-readable size (XL / medium)' },
            { property: 'sizeGroup', valueType: 'WearableSizeGroupEnumeration', status: 'Recommended', description: 'Regular | Petite | Plus | Tall' },
            { property: 'sizeSystem', valueType: 'WearableSizeSystemEnumeration', status: 'Recommended', description: 'US | EU | JP' },
        ],
    },
    SocialMediaPosting: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SocialMediaPosting' },
            { property: 'author', valueType: 'Person|Organization', status: 'Required', description: 'Post creator information' },
            { property: 'author.name', valueType: 'Text', status: 'Required', description: 'Creator name' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended', description: 'Link to creator profile' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required', description: 'ISO 8601 publication timestamp' },
            { property: 'text', valueType: 'Text', status: 'Required', description: 'Post content (required if no image/video)' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended', description: 'Inline post images' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended', description: 'Inline post videos' },
            { property: 'headline', valueType: 'Text', status: 'Recommended', description: 'Post title' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Canonical post URL' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended', description: 'Nested responses' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended', description: 'Total response count' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'Engagement metrics' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended', description: 'Last edit timestamp' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended', description: 'Status (e.g. Deleted)' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended', description: 'Content origin type' },
            { property: 'isPartOf', valueType: 'CreativeWork|URL', status: 'Recommended', description: 'Parent forum/subforum' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended', description: 'Referenced content' },
        ],
    },
    SoftwareApplication: {
        feature: 'SoftwareApp',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SoftwareApplication | MobileApplication | WebApplication | VideoGame' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Name of the app' },
            { property: 'offers', valueType: 'Offer', status: 'Required', description: 'Price information (0 if free)' },
            { property: 'offers.price', valueType: 'Number', status: 'Required', description: 'Price of the app (0 for free)' },
            { property: 'offers.priceCurrency', valueType: 'Text', status: 'Recommended', description: 'ISO 4217 currency code' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Average review score' },
            { property: 'review', valueType: 'Review', status: 'Recommended', description: 'Single app review' },
            { property: 'applicationCategory', valueType: 'Text', status: 'Recommended', description: 'GameApplication | BusinessApplication | EducationApplication | etc.' },
            { property: 'operatingSystem', valueType: 'Text', status: 'Recommended', description: 'Required OS (e.g. Android 1.6)' },
        ],
    },
    SolveMathAction: {
        feature: 'MathSolver',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SolveMathAction' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required', description: 'URL endpoint with {math_expression_string} placeholder' },
            { property: 'mathExpression-input', valueType: 'Text', status: 'Required', description: 'required name=math_expression_string' },
            { property: 'eduQuestionType', valueType: 'Text', status: 'Recommended', description: 'Problem types solvable by this action' },
        ],
    },
    SpeakableSpecification: {
        feature: 'Speakable',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'SpeakableSpecification' },
            { property: 'cssSelector', valueType: 'Text', status: 'Required', description: 'CSS selector addressing content for audio' },
            { property: 'xPath', valueType: 'Text', status: 'Required', description: 'XPath addressing content (alternative to cssSelector)' },
        ],
    },
    UnitPriceSpecification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'UnitPriceSpecification' },
            { property: 'price', valueType: 'Number', status: 'Required', description: 'Offer price amount' },
            { property: 'priceCurrency', valueType: 'Text', status: 'Required', description: 'ISO 4217 currency code' },
            { property: 'priceType', valueType: 'PriceTypeEnumeration', status: 'Recommended', description: 'StrikethroughPrice for sale pricing' },
            { property: 'membershipPointsEarned', valueType: 'Number', status: 'Recommended', description: 'Loyalty program points earned' },
            { property: 'referenceQuantity', valueType: 'QuantitativeValue', status: 'Recommended', description: 'Unit pricing base measurement' },
            { property: 'validForMemberTier', valueType: 'MemberProgramTier', status: 'Recommended', description: 'Loyalty tier price validity' },
        ],
    },
    VacationRental: {
        feature: 'VacationRental',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'VacationRental' },
            { property: 'identifier', valueType: 'Text', status: 'Required', description: 'Unique property identifier independent of listing content' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Vacation rental listing name' },
            { property: 'latitude', valueType: 'Number', status: 'Required', description: 'Latitude with at least 5 decimal places' },
            { property: 'longitude', valueType: 'Number', status: 'Required', description: 'Longitude with at least 5 decimal places' },
            { property: 'image', valueType: 'URL', status: 'Required', description: 'Minimum 8 photos (bedroom / bathroom / common area)' },
            { property: 'containsPlace', valueType: 'Accommodation', status: 'Required', description: 'Accommodation details' },
            { property: 'additionalType', valueType: 'Text', status: 'Recommended', description: 'Apartment | Cabin | Villa | etc.' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Property description' },
            { property: 'address', valueType: 'PostalAddress', status: 'Recommended', description: 'Full physical location' },
            { property: 'brand', valueType: 'Brand', status: 'Recommended', description: 'Brand ID association' },
            { property: 'checkinTime', valueType: 'Time', status: 'Recommended', description: 'Earliest check-in time (ISO 8601)' },
            { property: 'checkoutTime', valueType: 'Time', status: 'Recommended', description: 'Latest check-out time (ISO 8601)' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended', description: 'Average rating from multiple reviews' },
            { property: 'review', valueType: 'Review', status: 'Recommended', description: 'User reviews with datePublished required' },
            { property: 'knowsLanguage', valueType: 'Text', status: 'Recommended', description: 'Host languages using IETF BCP 47 codes' },
        ],
    },
    VideoObject: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', description: 'VideoObject' },
            { property: 'name', valueType: 'Text', status: 'Required', description: 'Video title (must be unique per video)' },
            { property: 'thumbnailUrl', valueType: 'URL', status: 'Required', description: 'URL to video unique thumbnail image' },
            { property: 'uploadDate', valueType: 'DateTime', status: 'Required', description: 'Publication date/time in ISO 8601' },
            { property: 'contentUrl', valueType: 'URL', status: 'Recommended', description: 'Direct URL to video file content bytes' },
            { property: 'description', valueType: 'Text', status: 'Recommended', description: 'Video description (must be unique per video)' },
            { property: 'duration', valueType: 'Duration', status: 'Recommended', description: 'Video length in ISO 8601 (e.g. PT1M54S)' },
            { property: 'embedUrl', valueType: 'URL', status: 'Recommended', description: 'URL to video player' },
            { property: 'expires', valueType: 'DateTime', status: 'Recommended', description: 'Date/time video becomes unavailable' },
            { property: 'hasPart', valueType: 'Clip', status: 'Recommended', description: 'Important video segments for navigation' },
            { property: 'ineligibleRegion', valueType: 'Place', status: 'Recommended', description: 'Countries where video is not allowed' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended', description: 'View count with WatchAction type' },
            { property: 'publication', valueType: 'BroadcastEvent', status: 'Recommended', description: 'For livestream videos with LIVE badge' },
            { property: 'regionsAllowed', valueType: 'Place', status: 'Recommended', description: 'Countries where video is permitted' },
        ],
    },
    WebPage: {
        feature: 'Speakable',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', description: 'https://schema.org' },
            { property: '@type', valueType: 'Text', status: 'Required', description: 'WebPage | Article' },
            { property: 'speakable', valueType: 'SpeakableSpecification', status: 'Recommended', description: 'Sections best suited for audio playback' },
            { property: 'name', valueType: 'Text', status: 'Recommended', description: 'Page or article title' },
            { property: 'url', valueType: 'URL', status: 'Recommended', description: 'Page URL' },
            { property: 'description', valueType: 'Text', status: 'Optional', description: 'Meta description content' },
        ],
    },
};

export const JSONLD_TYPE_NAMES: string[] = Object.keys(JSONLD_TYPES);
