export type JsonLdStatus = 'Required' | 'Recommended' | 'Optional' | 'Conditional';

export interface JsonLdPropertySpec {
    property: string;
    valueType: string;
    status: JsonLdStatus;
    enumValues?: string[];
}

export interface JsonLdTypeSpec {
    feature: string;
    properties: JsonLdPropertySpec[];
}

export const JSONLD_TYPES: Record<string, JsonLdTypeSpec> = {
    Accommodation: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Accommodation'] },
            { property: 'occupancy', valueType: 'QuantitativeValue', status: 'Required' },
            {
                property: 'additionalType',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: ['EntirePlace', 'PrivateRoom', 'SharedRoom'],
            },
            { property: 'bed', valueType: 'BedDetails', status: 'Recommended' },
            { property: 'amenityFeature', valueType: 'LocationFeatureSpecification', status: 'Recommended' },
            { property: 'floorSize', valueType: 'QuantitativeValue', status: 'Recommended' },
            { property: 'numberOfBathroomsTotal', valueType: 'Integer', status: 'Recommended' },
            { property: 'numberOfBedrooms', valueType: 'Integer', status: 'Recommended' },
            { property: 'numberOfRooms', valueType: 'Integer', status: 'Recommended' },
            { property: 'petsAllowed', valueType: 'Boolean', status: 'Optional' },
            { property: 'smokingAllowed', valueType: 'Boolean', status: 'Optional' },
        ],
    },
    AggregateRating: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['AggregateRating'] },
            { property: 'ratingValue', valueType: 'Number|Text', status: 'Required' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended' },
            { property: 'ratingCount', valueType: 'Number', status: 'Required' },
            { property: 'reviewCount', valueType: 'Number', status: 'Required' },
            { property: 'itemReviewed', valueType: 'Thing', status: 'Required' },
            { property: 'itemReviewed.name', valueType: 'Text', status: 'Required' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended' },
        ],
    },
    Answer: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Answer'] },
            { property: 'text', valueType: 'Text', status: 'Required' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'upvoteCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
        ],
    },
    Article: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            {
                property: '@type',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['Article', 'NewsArticle', 'BlogPosting'],
            },
            { property: 'headline', valueType: 'Text', status: 'Recommended' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional' },
        ],
    },
    BedDetails: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['BedDetails'] },
            { property: 'numberOfBeds', valueType: 'Integer', status: 'Recommended' },
            {
                property: 'typeOfBed',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: ['Queen', 'King', 'Single', 'Double'],
            },
        ],
    },
    BlogPosting: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['BlogPosting'] },
            { property: 'headline', valueType: 'Text', status: 'Recommended' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional' },
        ],
    },
    Book: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@id', valueType: 'Text', status: 'Required' },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Book'] },
            { property: 'author', valueType: 'Person|Organization', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            { property: 'workExample', valueType: 'Book', status: 'Required' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended' },
            {
                property: 'bookFormat',
                valueType: 'Enum',
                status: 'Required',
                enumValues: ['Audiobook', 'EBook', 'Hardcover', 'Paperback'],
            },
            { property: 'inLanguage', valueType: 'Text', status: 'Required' },
            { property: 'isbn', valueType: 'Text', status: 'Required' },
            { property: 'potentialAction', valueType: 'ReadAction|BorrowAction', status: 'Required' },
            { property: 'bookEdition', valueType: 'Text', status: 'Recommended' },
            { property: 'datePublished', valueType: 'Date', status: 'Recommended' },
            { property: 'identifier', valueType: 'PropertyValue', status: 'Recommended' },
        ],
    },
    BorrowAction: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['BorrowAction'] },
            { property: 'lender', valueType: 'LibrarySystem', status: 'Required' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required' },
            { property: 'target.@type', valueType: 'Text', status: 'Required', enumValues: ['EntryPoint'] },
            {
                property: 'target.actionPlatform',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['DesktopWeb', 'Android', 'iOS'],
            },
            { property: 'target.urlTemplate', valueType: 'URL', status: 'Required' },
        ],
    },
    Brand: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Brand'] },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
        ],
    },
    BreadcrumbList: {
        feature: 'Breadcrumb',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['BreadcrumbList'] },
            { property: 'itemListElement', valueType: 'ListItem[]', status: 'Required' },
        ],
    },
    BroadcastEvent: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['BroadcastEvent'] },
            { property: 'isLiveBroadcast', valueType: 'Boolean', status: 'Required' },
            { property: 'startDate', valueType: 'DateTime', status: 'Required' },
            { property: 'endDate', valueType: 'DateTime', status: 'Required' },
        ],
    },
    Certification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Certification'] },
            { property: 'issuedBy', valueType: 'Organization', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'certificationIdentification', valueType: 'Text', status: 'Recommended' },
            { property: 'certificationRating', valueType: 'Rating', status: 'Recommended' },
        ],
    },
    Claim: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Claim'] },
            { property: 'appearance', valueType: 'URL|CreativeWork', status: 'Recommended' },
            { property: 'author', valueType: 'Organization|Person', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime|Date', status: 'Recommended' },
            { property: 'firstAppearance', valueType: 'URL|CreativeWork', status: 'Recommended' },
        ],
    },
    ClaimReview: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ClaimReview'] },
            { property: 'claimReviewed', valueType: 'Text', status: 'Required' },
            { property: 'reviewRating', valueType: 'Rating', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            { property: 'author', valueType: 'Organization|Person', status: 'Recommended' },
            { property: 'itemReviewed', valueType: 'Claim|CreativeWork', status: 'Recommended' },
        ],
    },
    Clip: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Clip'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'startOffset', valueType: 'Number', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            { property: 'endOffset', valueType: 'Number', status: 'Recommended' },
        ],
    },
    Comment: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Comment'] },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.name', valueType: 'Text', status: 'Required' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required' },
            { property: 'text', valueType: 'Text', status: 'Required' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended' },
        ],
    },
    Course: {
        feature: 'CourseList',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'description', valueType: 'Text', status: 'Required' },
            { property: 'provider', valueType: 'Organization', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Optional' },
        ],
    },
    CreativeWork: {
        feature: 'PaywalledContent',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            {
                property: '@type',
                valueType: 'Text',
                status: 'Required',
                enumValues: [
                    'Article',
                    'NewsArticle',
                    'Blog',
                    'Comment',
                    'Course',
                    'HowTo',
                    'Message',
                    'Review',
                    'WebPage',
                ],
            },
            { property: 'isAccessibleForFree', valueType: 'Boolean', status: 'Required' },
            { property: 'hasPart', valueType: 'WebPageElement', status: 'Recommended' },
            { property: 'hasPart.@type', valueType: 'Text', status: 'Recommended', enumValues: ['WebPageElement'] },
            { property: 'hasPart.isAccessibleForFree', valueType: 'Boolean', status: 'Recommended' },
            { property: 'hasPart.cssSelector', valueType: 'CssSelectorType', status: 'Recommended' },
            { property: 'headline', valueType: 'Text', status: 'Optional' },
            { property: 'image', valueType: 'URL', status: 'Optional' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Optional' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Optional' },
            { property: 'author', valueType: 'Person', status: 'Optional' },
            { property: 'description', valueType: 'Text', status: 'Optional' },
            { property: 'mainEntityOfPage', valueType: 'WebPage', status: 'Optional' },
        ],
    },
    DataCatalog: {
        feature: 'Dataset',
        properties: [{ property: 'includedInDataCatalog', valueType: 'DataCatalog', status: 'Recommended' }],
    },
    DataDownload: {
        feature: 'Dataset',
        properties: [
            { property: 'distribution', valueType: 'DataDownload', status: 'Recommended' },
            { property: 'distribution.contentUrl', valueType: 'URL', status: 'Required' },
            { property: 'distribution.encodingFormat', valueType: 'Text|URL', status: 'Recommended' },
        ],
    },
    DataFeed: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['DataFeed'] },
            { property: 'dataFeedElement', valueType: 'Book|LibrarySystem', status: 'Required' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Required' },
        ],
    },
    Dataset: {
        feature: 'Dataset',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'description', valueType: 'Text', status: 'Required' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended' },
            { property: 'creator', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'citation', valueType: 'Text|CreativeWork', status: 'Recommended' },
            { property: 'funder', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'hasPart', valueType: 'URL|Dataset', status: 'Recommended' },
            { property: 'isPartOf', valueType: 'URL|Dataset', status: 'Recommended' },
            { property: 'identifier', valueType: 'URL|Text|PropertyValue', status: 'Recommended' },
            { property: 'isAccessibleForFree', valueType: 'Boolean', status: 'Recommended' },
            { property: 'keywords', valueType: 'Text', status: 'Recommended' },
            { property: 'license', valueType: 'URL|CreativeWork', status: 'Recommended' },
            { property: 'measurementTechnique', valueType: 'Text|URL', status: 'Recommended' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended' },
            { property: 'spatialCoverage', valueType: 'Text|Place', status: 'Recommended' },
            { property: 'temporalCoverage', valueType: 'Text', status: 'Recommended' },
            { property: 'variableMeasured', valueType: 'Text|PropertyValue', status: 'Recommended' },
            { property: 'version', valueType: 'Text|Number', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
        ],
    },
    DiscussionForumPosting: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            {
                property: '@type',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['DiscussionForumPosting', 'SocialMediaPosting'],
            },
            { property: 'author', valueType: 'Person|Organization', status: 'Required' },
            { property: 'author.name', valueType: 'Text', status: 'Required' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required' },
            { property: 'text', valueType: 'Text', status: 'Required' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
            { property: 'headline', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended' },
            { property: 'isPartOf', valueType: 'CreativeWork|URL', status: 'Recommended' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended' },
        ],
    },
    EmployerAggregateRating: {
        feature: 'EmployerRating',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['EmployerAggregateRating'] },
            { property: 'itemReviewed', valueType: 'Organization', status: 'Required' },
            { property: 'ratingCount', valueType: 'Number', status: 'Required' },
            { property: 'ratingValue', valueType: 'Number|Text', status: 'Required' },
            { property: 'reviewCount', valueType: 'Number', status: 'Required' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended' },
        ],
    },
    Event: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Event'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'startDate', valueType: 'DateTime', status: 'Required' },
            { property: 'location', valueType: 'Place', status: 'Required' },
            { property: 'location.address', valueType: 'PostalAddress', status: 'Required' },
            { property: 'location.name', valueType: 'Text', status: 'Recommended' },
            { property: 'endDate', valueType: 'DateTime', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            {
                property: 'eventStatus',
                valueType: 'EventStatusType',
                status: 'Recommended',
                enumValues: [
                    'EventScheduled',
                    'EventCancelled',
                    'EventMovedOnline',
                    'EventPostponed',
                    'EventRescheduled',
                ],
            },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'offers', valueType: 'Offer', status: 'Recommended' },
            { property: 'organizer', valueType: 'Organization|Person', status: 'Recommended' },
            { property: 'performer', valueType: 'Person|PerformingGroup', status: 'Recommended' },
            { property: 'previousStartDate', valueType: 'DateTime', status: 'Optional' },
        ],
    },
    FAQPage: {
        feature: 'FAQ',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['FAQPage'] },
            { property: 'mainEntity', valueType: 'Question[]', status: 'Required' },
        ],
    },
    HowToDirection: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['HowToDirection'] },
            { property: 'text', valueType: 'Text', status: 'Required' },
        ],
    },
    HowToSection: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['HowToSection'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'itemListElement', valueType: 'HowToStep[]', status: 'Required' },
        ],
    },
    HowToStep: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['HowToStep'] },
            { property: 'text', valueType: 'Text', status: 'Required' },
            { property: 'itemListElement', valueType: 'HowToDirection[]|HowToTip[]', status: 'Optional' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject|Clip', status: 'Recommended' },
        ],
    },
    HowToTip: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['HowToTip'] },
            { property: 'text', valueType: 'Text', status: 'Required' },
        ],
    },
    ImageObject: {
        feature: 'ImageMetadata',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ImageObject'] },
            { property: 'contentUrl', valueType: 'URL', status: 'Required' },
            { property: 'creator', valueType: 'Organization|Person', status: 'Required' },
            { property: 'creator.name', valueType: 'Text', status: 'Required' },
            { property: 'creditText', valueType: 'Text', status: 'Required' },
            { property: 'copyrightNotice', valueType: 'Text', status: 'Required' },
            { property: 'license', valueType: 'URL', status: 'Required' },
            { property: 'acquireLicensePage', valueType: 'URL', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Optional' },
        ],
    },
    InteractionCounter: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['InteractionCounter'] },
            { property: 'userInteractionCount', valueType: 'Number', status: 'Required' },
            {
                property: 'interactionType',
                valueType: 'Action',
                status: 'Required',
                enumValues: [
                    'LikeAction',
                    'DislikeAction',
                    'ViewAction',
                    'CommentAction',
                    'ReplyAction',
                    'ShareAction',
                ],
            },
        ],
    },
    ItemList: {
        feature: 'Carousel',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ItemList'] },
            { property: 'itemListElement', valueType: 'ListItem[]', status: 'Required' },
        ],
    },
    JobPosting: {
        feature: 'JobPosting',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['JobPosting'] },
            { property: 'datePosted', valueType: 'Date', status: 'Required' },
            { property: 'description', valueType: 'Text', status: 'Required' },
            { property: 'hiringOrganization', valueType: 'Organization', status: 'Required' },
            { property: 'jobLocation', valueType: 'Place', status: 'Required' },
            { property: 'title', valueType: 'Text', status: 'Required' },
            { property: 'applicantLocationRequirements', valueType: 'AdministrativeArea', status: 'Recommended' },
            { property: 'baseSalary', valueType: 'MonetaryAmount', status: 'Recommended' },
            { property: 'directApply', valueType: 'Boolean', status: 'Recommended' },
            {
                property: 'employmentType',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: [
                    'FULL_TIME',
                    'PART_TIME',
                    'CONTRACTOR',
                    'TEMPORARY',
                    'INTERN',
                    'VOLUNTEER',
                    'PER_DIEM',
                    'OTHER',
                ],
            },
            { property: 'identifier', valueType: 'PropertyValue', status: 'Recommended' },
            { property: 'jobLocationType', valueType: 'Text', status: 'Recommended' },
            { property: 'validThrough', valueType: 'DateTime', status: 'Recommended' },
            { property: 'educationRequirements', valueType: 'EducationalOccupationalCredential', status: 'Optional' },
            { property: 'experienceRequirements', valueType: 'OccupationalExperienceRequirements', status: 'Optional' },
            { property: 'experienceInPlaceOfEducation', valueType: 'Boolean', status: 'Optional' },
        ],
    },
    Library: {
        feature: 'Book',
        properties: [
            { property: '@id', valueType: 'URL', status: 'Required' },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Library'] },
            { property: 'location', valueType: 'PostalAddress', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'location.@type', valueType: 'Text', status: 'Required', enumValues: ['PostalAddress'] },
            { property: 'location.addressCountry', valueType: 'Text', status: 'Required' },
            { property: 'location.addressLocality', valueType: 'Text', status: 'Required' },
            { property: 'location.addressRegion', valueType: 'Text', status: 'Required' },
            { property: 'location.postalCode', valueType: 'Text', status: 'Required' },
            { property: 'location.streetAddress', valueType: 'Text', status: 'Required' },
        ],
    },
    LibrarySystem: {
        feature: 'Book',
        properties: [
            { property: '@context', valueType: 'Text', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@id', valueType: 'URL', status: 'Required' },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['LibrarySystem'] },
            { property: 'additionalProperty', valueType: 'PropertyValue', status: 'Required' },
            { property: 'member', valueType: 'Library', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            {
                property: 'additionalProperty.@type',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['PropertyValue'],
            },
            { property: 'additionalProperty.name', valueType: 'Text', status: 'Required', enumValues: ['librarytype'] },
            {
                property: 'additionalProperty.value',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['public', 'academic', 'corporate', 'government', 'school', 'special'],
            },
        ],
    },
    ListItem: {
        feature: 'Breadcrumb',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ListItem'] },
            { property: 'position', valueType: 'Integer', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'item', valueType: 'URL|Thing', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            { property: 'item.name', valueType: 'Text', status: 'Required' },
            { property: 'item.url', valueType: 'URL', status: 'Required' },
        ],
    },
    LocalBusiness: {
        feature: 'LocalBusiness',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'address', valueType: 'PostalAddress', status: 'Required' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
            { property: 'department', valueType: 'LocalBusiness', status: 'Recommended' },
            { property: 'geo', valueType: 'GeoCoordinates', status: 'Recommended' },
            { property: 'menu', valueType: 'URL', status: 'Recommended' },
            { property: 'openingHoursSpecification', valueType: 'OpeningHoursSpecification', status: 'Recommended' },
            { property: 'priceRange', valueType: 'Text', status: 'Recommended' },
            { property: 'review', valueType: 'Review', status: 'Recommended' },
            { property: 'servesCuisine', valueType: 'Text', status: 'Recommended' },
            { property: 'telephone', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Optional' },
        ],
    },
    LocationFeatureSpecification: {
        feature: 'VacationRental',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['LocationFeatureSpecification'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'value', valueType: 'Boolean|Text', status: 'Required' },
        ],
    },
    MathSolver: {
        feature: 'MathSolver',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Required' },
            { property: 'usageInfo', valueType: 'URL', status: 'Required' },
            { property: 'inLanguage', valueType: 'Text', status: 'Recommended' },
            { property: 'potentialAction', valueType: 'SolveMathAction', status: 'Required' },
            { property: 'assesses', valueType: 'Text', status: 'Recommended' },
            { property: 'learningResourceType', valueType: 'Text', status: 'Required' },
        ],
    },
    MonetaryAmount: {
        feature: 'JobPosting',
        properties: [
            { property: 'currency', valueType: 'Text', status: 'Required' },
            { property: 'value', valueType: 'QuantitativeValue', status: 'Required' },
        ],
    },
    Movie: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Movie'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'dateCreated', valueType: 'Date|DateTime', status: 'Recommended' },
            { property: 'director', valueType: 'Person', status: 'Recommended' },
            { property: 'review', valueType: 'Review', status: 'Recommended' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
        ],
    },
    NewsArticle: {
        feature: 'Article',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['NewsArticle'] },
            { property: 'headline', valueType: 'Text', status: 'Recommended' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.name', valueType: 'Text', status: 'Recommended' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional' },
        ],
    },
    Offer: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Offer'] },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'price', valueType: 'Number', status: 'Recommended' },
            { property: 'priceCurrency', valueType: 'Text', status: 'Required' },
            {
                property: 'availability',
                valueType: 'ItemAvailability',
                status: 'Recommended',
                enumValues: ['InStock', 'OutOfStock', 'PreOrder', 'Discontinued'],
            },
            { property: 'validFrom', valueType: 'DateTime', status: 'Recommended' },
            { property: 'priceSpecification', valueType: 'UnitPriceSpecification', status: 'Optional' },
            { property: 'hasMerchantReturnPolicy', valueType: 'MerchantReturnPolicy', status: 'Recommended' },
            {
                property: 'itemCondition',
                valueType: 'OfferItemCondition',
                status: 'Recommended',
                enumValues: ['NewCondition', 'UsedCondition', 'RefurbishedCondition'],
            },
            { property: 'priceValidUntil', valueType: 'Date', status: 'Recommended' },
            { property: 'shippingDetails', valueType: 'OfferShippingDetails', status: 'Recommended' },
        ],
    },
    OfferShippingDetails: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['OfferShippingDetails'] },
            { property: 'shippingRate', valueType: 'MonetaryAmount', status: 'Recommended' },
            { property: 'shippingDestination', valueType: 'DefinedRegion', status: 'Recommended' },
            { property: 'deliveryTime', valueType: 'ShippingDeliveryTime', status: 'Recommended' },
        ],
    },
    OpeningHoursSpecification: {
        feature: 'LocalBusiness',
        properties: [
            { property: 'closes', valueType: 'Time', status: 'Recommended' },
            {
                property: 'dayOfWeek',
                valueType: 'DayOfWeek',
                status: 'Recommended',
                enumValues: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            },
            { property: 'opens', valueType: 'Time', status: 'Recommended' },
            { property: 'validFrom', valueType: 'Date', status: 'Recommended' },
            { property: 'validThrough', valueType: 'Date', status: 'Recommended' },
        ],
    },
    Organization: {
        feature: 'CourseList',
        properties: [
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended' },
            { property: 'logo', valueType: 'URL|ImageObject', status: 'Recommended' },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Organization'] },
            { property: 'address', valueType: 'PostalAddress', status: 'Recommended' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended' },
            { property: 'contactPoint', valueType: 'ContactPoint', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'email', valueType: 'Text', status: 'Recommended' },
            { property: 'foundingDate', valueType: 'Date', status: 'Recommended' },
            { property: 'globalLocationNumber', valueType: 'Text', status: 'Recommended' },
            { property: 'hasMerchantReturnPolicy', valueType: 'MerchantReturnPolicy', status: 'Recommended' },
            { property: 'hasMemberProgram', valueType: 'MemberProgram', status: 'Recommended' },
            { property: 'hasShippingService', valueType: 'ShippingService', status: 'Recommended' },
            { property: 'iso6523Code', valueType: 'Text', status: 'Recommended' },
            { property: 'legalName', valueType: 'Text', status: 'Recommended' },
            { property: 'leiCode', valueType: 'Text', status: 'Recommended' },
            { property: 'numberOfEmployees', valueType: 'QuantitativeValue', status: 'Recommended' },
            { property: 'telephone', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'vatID', valueType: 'Text', status: 'Recommended' },
            { property: 'duns', valueType: 'Text', status: 'Optional' },
            { property: 'naics', valueType: 'Text', status: 'Optional' },
            { property: 'taxID', valueType: 'Text', status: 'Optional' },
        ],
    },
    PeopleAudience: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['PeopleAudience'] },
            {
                property: 'suggestedGender',
                valueType: 'Text|GenderType',
                status: 'Recommended',
                enumValues: ['Male', 'Female', 'Unisex'],
            },
            { property: 'suggestedMinAge', valueType: 'Number', status: 'Recommended' },
            { property: 'suggestedMaxAge', valueType: 'Number', status: 'Recommended' },
        ],
    },
    Person: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Person'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'alternateName', valueType: 'Text', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'identifier', valueType: 'Text', status: 'Recommended' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Recommended' },
            { property: 'sameAs', valueType: 'URL', status: 'Recommended' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
            { property: 'agentInteractionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
        ],
    },
    Place: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Place'] },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
            { property: 'address', valueType: 'PostalAddress', status: 'Required' },
        ],
    },
    PostalAddress: {
        feature: 'Event',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['PostalAddress'] },
            { property: 'streetAddress', valueType: 'Text', status: 'Recommended' },
            { property: 'addressLocality', valueType: 'Text', status: 'Recommended' },
            { property: 'addressRegion', valueType: 'Text', status: 'Recommended' },
            { property: 'postalCode', valueType: 'Text', status: 'Recommended' },
            { property: 'addressCountry', valueType: 'Text', status: 'Recommended' },
        ],
    },
    Product: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Product'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required' },
            { property: 'offers', valueType: 'Offer', status: 'Required' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
            { property: 'audience', valueType: 'PeopleAudience', status: 'Recommended' },
            { property: 'brand', valueType: 'Brand', status: 'Recommended' },
            { property: 'color', valueType: 'Text', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'gtin', valueType: 'Text', status: 'Recommended' },
            { property: 'gtin8', valueType: 'Text', status: 'Recommended' },
            { property: 'gtin12', valueType: 'Text', status: 'Recommended' },
            { property: 'gtin13', valueType: 'Text', status: 'Recommended' },
            { property: 'gtin14', valueType: 'Text', status: 'Recommended' },
            { property: 'hasCertification', valueType: 'Certification', status: 'Recommended' },
            { property: 'inProductGroupWithID', valueType: 'Text', status: 'Recommended' },
            { property: 'isVariantOf', valueType: 'ProductGroup', status: 'Recommended' },
            { property: 'material', valueType: 'Text', status: 'Recommended' },
            { property: 'mpn', valueType: 'Text', status: 'Recommended' },
            { property: 'pattern', valueType: 'Text', status: 'Recommended' },
            { property: 'review', valueType: 'Review', status: 'Recommended' },
            { property: 'size', valueType: 'Text|SizeSpecification', status: 'Recommended' },
            { property: 'sku', valueType: 'Text', status: 'Recommended' },
            { property: 'subjectOf', valueType: '3DModel', status: 'Recommended' },
        ],
    },
    ProfilePage: {
        feature: 'ProfilePage',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ProfilePage'] },
            { property: 'mainEntity', valueType: 'Person|Organization', status: 'Required' },
            { property: 'dateCreated', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'hasPart', valueType: 'Article', status: 'Optional' },
        ],
    },
    PropertyValue: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['PropertyValue'] },
            { property: 'propertyID', valueType: 'Text', status: 'Required' },
            { property: 'value', valueType: 'Text', status: 'Required' },
        ],
    },
    QAPage: {
        feature: 'QAPage',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['QAPage'] },
            { property: 'mainEntity', valueType: 'Question', status: 'Required' },
        ],
    },
    Question: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Question'] },
            { property: 'acceptedAnswer', valueType: 'Answer', status: 'Conditional' },
            { property: 'eduQuestionType', valueType: 'Text', status: 'Required', enumValues: ['Flashcard'] },
            { property: 'text', valueType: 'Text', status: 'Recommended' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'answerCount', valueType: 'Integer', status: 'Required' },
            { property: 'suggestedAnswer', valueType: 'Answer', status: 'Conditional' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'upvoteCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
        ],
    },
    Quiz: {
        feature: 'EducationQA',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Quiz'] },
            { property: 'hasPart', valueType: 'Question', status: 'Required' },
            { property: 'about', valueType: 'Thing', status: 'Recommended' },
            { property: 'about.name', valueType: 'Text', status: 'Recommended' },
            { property: 'educationalAlignment', valueType: 'AlignmentObject', status: 'Recommended' },
            {
                property: 'educationalAlignment.alignmentType',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: ['educationalSubject', 'educationalLevel'],
            },
            { property: 'educationalAlignment.targetName', valueType: 'Text', status: 'Recommended' },
        ],
    },
    Rating: {
        feature: 'FactCheck',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Rating'] },
            { property: 'alternateName', valueType: 'Text', status: 'Required' },
            { property: 'ratingValue', valueType: 'Number', status: 'Recommended' },
            { property: 'bestRating', valueType: 'Number', status: 'Recommended' },
            { property: 'worstRating', valueType: 'Number', status: 'Recommended' },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
        ],
    },
    ReadAction: {
        feature: 'Book',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['ReadAction'] },
            { property: 'expectsAcceptanceOf', valueType: 'Offer', status: 'Required' },
            { property: 'target', valueType: 'EntryPoint', status: 'Required' },
            { property: 'expectsAcceptanceOf.@type', valueType: 'Text', status: 'Required', enumValues: ['Offer'] },
            {
                property: 'expectsAcceptanceOf.category',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['nologinrequired', 'free', 'subscription', 'purchase', 'rental'],
            },
            { property: 'expectsAcceptanceOf.eligibleRegion', valueType: 'Country', status: 'Required' },
            { property: 'expectsAcceptanceOf.availabilityEnds', valueType: 'DateTime', status: 'Recommended' },
            { property: 'expectsAcceptanceOf.availabilityStarts', valueType: 'DateTime', status: 'Recommended' },
            { property: 'expectsAcceptanceOf.price', valueType: 'Number', status: 'Recommended' },
            { property: 'expectsAcceptanceOf.priceCurrency', valueType: 'Text', status: 'Recommended' },
            { property: 'target.@type', valueType: 'Text', status: 'Required', enumValues: ['EntryPoint'] },
            {
                property: 'target.actionPlatform',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['DesktopWeb', 'Android', 'iOS'],
            },
            { property: 'target.urlTemplate', valueType: 'URL', status: 'Required' },
        ],
    },
    Recipe: {
        feature: 'Recipe',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Recipe'] },
            { property: 'image', valueType: 'URL|ImageObject', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
            { property: 'author', valueType: 'Person|Organization', status: 'Recommended' },
            { property: 'cookTime', valueType: 'Duration', status: 'Recommended' },
            { property: 'datePublished', valueType: 'Date', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'keywords', valueType: 'Text', status: 'Recommended' },
            { property: 'nutrition.calories', valueType: 'Energy', status: 'Recommended' },
            { property: 'prepTime', valueType: 'Duration', status: 'Recommended' },
            { property: 'recipeCategory', valueType: 'Text', status: 'Recommended' },
            { property: 'recipeCuisine', valueType: 'Text', status: 'Recommended' },
            { property: 'recipeIngredient', valueType: 'Text', status: 'Recommended' },
            { property: 'recipeInstructions', valueType: 'HowToStep|HowToSection|Text', status: 'Recommended' },
            { property: 'recipeYield', valueType: 'Text|Integer', status: 'Recommended' },
            { property: 'totalTime', valueType: 'Duration', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
        ],
    },
    Review: {
        feature: 'Movie',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['Review'] },
            { property: 'reviewRating', valueType: 'Rating', status: 'Required' },
            { property: 'author', valueType: 'Person|Organization', status: 'Required' },
            { property: 'positiveNotes', valueType: 'ItemList', status: 'Optional' },
            { property: 'negativeNotes', valueType: 'ItemList', status: 'Optional' },
            { property: 'itemReviewed', valueType: 'Thing', status: 'Required' },
            { property: 'itemReviewed.name', valueType: 'Text', status: 'Required' },
            { property: 'reviewRating.ratingValue', valueType: 'Number|Text', status: 'Required' },
            { property: 'datePublished', valueType: 'Date', status: 'Required' },
            { property: 'reviewRating.bestRating', valueType: 'Number', status: 'Recommended' },
            { property: 'reviewRating.worstRating', valueType: 'Number', status: 'Recommended' },
            { property: 'publisher', valueType: 'Organization', status: 'Optional' },
            { property: 'contentReferenceTime', valueType: 'DateTime', status: 'Required' },
        ],
    },
    SeekToAction: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['SeekToAction'] },
            { property: 'target', valueType: 'EntryPoint', status: 'Required' },
            { property: 'startOffset-input', valueType: 'Text', status: 'Required' },
        ],
    },
    SizeSpecification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['SizeSpecification'] },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
            {
                property: 'sizeGroup',
                valueType: 'WearableSizeGroupEnumeration',
                status: 'Recommended',
                enumValues: ['Regular', 'Petite', 'Plus', 'Tall'],
            },
            {
                property: 'sizeSystem',
                valueType: 'WearableSizeSystemEnumeration',
                status: 'Recommended',
                enumValues: ['US', 'EU', 'JP'],
            },
        ],
    },
    SocialMediaPosting: {
        feature: 'DiscussionForum',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['SocialMediaPosting'] },
            { property: 'author', valueType: 'Person|Organization', status: 'Required' },
            { property: 'author.name', valueType: 'Text', status: 'Required' },
            { property: 'author.url', valueType: 'URL', status: 'Recommended' },
            { property: 'datePublished', valueType: 'DateTime', status: 'Required' },
            { property: 'text', valueType: 'Text', status: 'Required' },
            { property: 'image', valueType: 'ImageObject|URL', status: 'Recommended' },
            { property: 'video', valueType: 'VideoObject', status: 'Recommended' },
            { property: 'headline', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'comment', valueType: 'Comment', status: 'Recommended' },
            { property: 'commentCount', valueType: 'Integer', status: 'Recommended' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
            { property: 'dateModified', valueType: 'DateTime', status: 'Recommended' },
            { property: 'creativeWorkStatus', valueType: 'Text', status: 'Recommended' },
            { property: 'digitalSourceType', valueType: 'IPTCDigitalSourceEnumeration', status: 'Recommended' },
            { property: 'isPartOf', valueType: 'CreativeWork|URL', status: 'Recommended' },
            { property: 'sharedContent', valueType: 'CreativeWork', status: 'Recommended' },
        ],
    },
    SoftwareApplication: {
        feature: 'SoftwareApp',
        properties: [
            {
                property: '@type',
                valueType: 'Text',
                status: 'Required',
                enumValues: ['SoftwareApplication', 'MobileApplication', 'WebApplication', 'VideoGame'],
            },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'offers', valueType: 'Offer', status: 'Required' },
            { property: 'offers.price', valueType: 'Number', status: 'Required' },
            { property: 'offers.priceCurrency', valueType: 'Text', status: 'Recommended' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
            { property: 'review', valueType: 'Review', status: 'Recommended' },
            {
                property: 'applicationCategory',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: ['GameApplication', 'BusinessApplication', 'EducationApplication'],
            },
            { property: 'operatingSystem', valueType: 'Text', status: 'Recommended' },
        ],
    },
    SolveMathAction: {
        feature: 'MathSolver',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['SolveMathAction'] },
            { property: 'target', valueType: 'EntryPoint', status: 'Required' },
            { property: 'mathExpression-input', valueType: 'Text', status: 'Required' },
            { property: 'eduQuestionType', valueType: 'Text', status: 'Recommended' },
        ],
    },
    SpeakableSpecification: {
        feature: 'Speakable',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['SpeakableSpecification'] },
            { property: 'cssSelector', valueType: 'Text', status: 'Required' },
            { property: 'xPath', valueType: 'Text', status: 'Required' },
        ],
    },
    UnitPriceSpecification: {
        feature: 'Product',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['UnitPriceSpecification'] },
            { property: 'price', valueType: 'Number', status: 'Required' },
            { property: 'priceCurrency', valueType: 'Text', status: 'Required' },
            { property: 'priceType', valueType: 'PriceTypeEnumeration', status: 'Recommended' },
            { property: 'membershipPointsEarned', valueType: 'Number', status: 'Recommended' },
            { property: 'referenceQuantity', valueType: 'QuantitativeValue', status: 'Recommended' },
            { property: 'validForMemberTier', valueType: 'MemberProgramTier', status: 'Recommended' },
        ],
    },
    VacationRental: {
        feature: 'VacationRental',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['VacationRental'] },
            { property: 'identifier', valueType: 'Text', status: 'Required' },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'latitude', valueType: 'Number', status: 'Required' },
            { property: 'longitude', valueType: 'Number', status: 'Required' },
            { property: 'image', valueType: 'URL', status: 'Required' },
            { property: 'containsPlace', valueType: 'Accommodation', status: 'Required' },
            {
                property: 'additionalType',
                valueType: 'Text',
                status: 'Recommended',
                enumValues: ['Apartment', 'Cabin', 'Villa'],
            },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'address', valueType: 'PostalAddress', status: 'Recommended' },
            { property: 'brand', valueType: 'Brand', status: 'Recommended' },
            { property: 'checkinTime', valueType: 'Time', status: 'Recommended' },
            { property: 'checkoutTime', valueType: 'Time', status: 'Recommended' },
            { property: 'aggregateRating', valueType: 'AggregateRating', status: 'Recommended' },
            { property: 'review', valueType: 'Review', status: 'Recommended' },
            { property: 'knowsLanguage', valueType: 'Text', status: 'Recommended' },
        ],
    },
    VideoObject: {
        feature: 'Video',
        properties: [
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['VideoObject'] },
            { property: 'name', valueType: 'Text', status: 'Required' },
            { property: 'thumbnailUrl', valueType: 'URL', status: 'Required' },
            { property: 'uploadDate', valueType: 'DateTime', status: 'Required' },
            { property: 'contentUrl', valueType: 'URL', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Recommended' },
            { property: 'duration', valueType: 'Duration', status: 'Recommended' },
            { property: 'embedUrl', valueType: 'URL', status: 'Recommended' },
            { property: 'expires', valueType: 'DateTime', status: 'Recommended' },
            { property: 'hasPart', valueType: 'Clip', status: 'Recommended' },
            { property: 'ineligibleRegion', valueType: 'Place', status: 'Recommended' },
            { property: 'interactionStatistic', valueType: 'InteractionCounter', status: 'Recommended' },
            { property: 'publication', valueType: 'BroadcastEvent', status: 'Recommended' },
            { property: 'regionsAllowed', valueType: 'Place', status: 'Recommended' },
        ],
    },
    WebPage: {
        feature: 'Speakable',
        properties: [
            { property: '@context', valueType: 'URL', status: 'Required', enumValues: ['https://schema.org'] },
            { property: '@type', valueType: 'Text', status: 'Required', enumValues: ['WebPage', 'Article'] },
            { property: 'speakable', valueType: 'SpeakableSpecification', status: 'Recommended' },
            { property: 'name', valueType: 'Text', status: 'Recommended' },
            { property: 'url', valueType: 'URL', status: 'Recommended' },
            { property: 'description', valueType: 'Text', status: 'Optional' },
        ],
    },
};

export const JSONLD_TYPE_NAMES: string[] = Object.keys(JSONLD_TYPES);
